notebook class and commands
RSMNYS/iBook pull request #18
Opened 2024-03-12 20:14 UTC by dan-bull

Вже є всі функції по тегам і заголовкам.

2024-03-12 21:03 UTC, RSMNYS requested changes

2024-03-13 06:42 UTC, dan-bull commented on src/notes_book/notes_commands.py
> +def main():
@RSMNYS Привіт, я переробив, можеш будь ласка подивитись в комітах?

2024-03-13 06:42 UTC, dan-bull commented on src/notes_book/notes.py
> +class Notebook(UserDict):
@RSMNYS Привіт, я переробив, можеш будь ласка подивитись в комітах?

2024-03-13 08:26 UTC, RSMNYS requested changes

2024-03-13 08:26 UTC, RSMNYS commented on src/notes_book/notes_commands_disp.py
> +from notes_commands import AddNoteCommand, EditNoteCommand, DeleteNoteCommand, SearchNoteByTitleCommand, AddTagCommand, EditTagCommand, SearchNoteByTagCommand
цього окремим модулем не потрібно. Всі команди, що стосується notes додай до вже існуючого commandDispatcher. Ми окремо notes не запускаємо.

2024-03-13 08:35 UTC, dan-bull commented on src/notes_book/notes_commands_disp.py
> +from notes_commands import AddNoteCommand, EditNoteCommand, DeleteNoteCommand, SearchNoteByTitleCommand, AddTagCommand, EditTagCommand, SearchNoteByTagCommand
@RSMNYS Я додав команди до існуючого, тільки чогось не працює import і я не розумію чого.

2024-03-13 15:19 UTC, closed without merging